#   This script analyzes the difference between an outputted with a FE grid and
# Another inputed image.
#
import numpy as np
import math

def get_distance(dist_funct, generated_image, exptl_image):
    ''' Returns the 'distance' or error (normalized) between two images.
        Takes in a distance function,
        takes in an image generated by FE solver and processed,
        takes in an image given by experimental imaging, ang processed.

        Returns a number  - the normalized 'difference'
        '''

def dist_funct(image1, image2):
    ''' Takes in two processed images, returns a distance between them.
    Note: this should represent the differences in how one image appears to be
    evolving vs the other
        '''
def image_processor(image):
    ''' reads in an image (from file), processes it to a form usable by the
        distance function, above.
        Likely have to strip away a lot of detail.
        '''

###############################################################################

def main():
	''' stuff '''

if __name__ == "__main__"
	main()
